steps:
  # Build the container image
  - name: gcr.io/cloud-builders/docker
    args: [ build, -t, gcr.io/$PROJECT_ID/ghost, --build-arg, DB_HOST=$$HOST, --build-arg, DB_PORT=$$PORT, --build-arg, DB_USER=$$USER, --build-arg, DB_PASS=$$PASSWORD, --build-arg, DB_NAME=$$DB_NAME, . ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ghost:latest']
  # Deploy New Cloud Run Version 
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', "$$SERVICE_NAME", '--image', 'gcr.io/$PROJECT_ID/ghost:latest', '--region', 'europe-west1', '--platform', 'managed']
    secretEnv: ['HOST', 'DB_NAME', 'PASSWORD', 'PORT', 'USER', 'SERVICE_NAME']

images:
- gcr.io/$PROJECT_ID/ghost
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/DB_HOST/versions/latest
    env: 'HOST'
  - versionName: projects/$PROJECT_ID/secrets/DB_NAME/versions/latest
    env: 'DB_NAME'
  - versionName: projects/$PROJECT_ID/secrets/DB_PASS/versions/latest
    env: 'PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/DB_PORT/versions/latest
    env: 'PORT'
  - versionName: projects/$PROJECT_ID/secrets/DB_USER/versions/latest
    env: 'USER'
  - versionName: projects/$PROJECT_ID/secrets/SERVICE_NAME/versions/latest
    env: 'SERVICE_NAME'
