steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ghost', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ghost:latest']
# Deploy New Cloud Run Version 
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'gcloud run deploy $$SERVICE_NAME --image gcr.io/$PROJECT_ID/ghost:latest --region europe-west1 --platform managed']
  secretEnv: [ 'SERVICE_NAME' ]
images:
- gcr.io/$PROJECT_ID/ghost
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SERVICE_NAME/versions/latest
    env: 'SERVICE_NAME'
